# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: t2m-staging-api

on:
  # push:
    # branches:
      # - master
      
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      working-directory: 'api'
      run: dotnet build --configuration Release

    - name: dotnet publish
      working-directory: 'api'
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: t2m-staging-api
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_STAGING_API_PUBLISHPROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp

