# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: t2m-prod-web

on:
  # push:
    # branches:
      # - master
      
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.19.0'

    - name: npm install, build, and test
      working-directory: 'web'
      run: |
        npm install
        CI='' npm run build --if-present
        
    - name: add process.json
      working-directory: 'web'
      run: |
        echo '{ script: "serve", env: { PM2_SERVE_SPA: "true", PM2_SERVE_HOMEPAGE: "/index.html" } }' >> build/process.json

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: lingua-web
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_PROD_WEB_PUBLISHPROFILE }}
        package: './web/build/'

